ppe42-gcc: Add build fix
When building with GCC 11, which defaults to C++17:

../.././gcc/reload1.c: In function ‘void init_reload()’:
../.././gcc/reload1.c:89:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17
   89 |   (this_target_reload->x_spill_indirect_levels)
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
../.././gcc/reload1.c:444:7: note: in expansion of macro ‘spill_indirect_levels’
  444 |       spill_indirect_levels++;
      |       ^~~~~~~~~~~~~~~~~~~~~

Make the same fix as was made upstream:

 https://github.com/gcc-mirror/gcc/commit/d57c99458933a21fdf94f508191f145ad8d5ec58

Signed-off-by: Joel Stanley <joel@jms.id.au>
(cherry picked from open-power/op-build commit ce22eadcecb601d00be4a484546a5d9eff632127)
Signed-off-by: Reza Arbab <arbab@linux.ibm.com>